// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1PuoZPnG-tE3X8uBfA6wiaOAE44pwMU',
    appId: '1:688257544869:ios:8ab67bf72283e525d3d34c',
    messagingSenderId: '688257544869',
    projectId: 'lost-found-22796',
    storageBucket: 'lost-found-22796.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
    databaseURL: 'https://lost-found-22796-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATqmZ8l53kMoTdkFAfdsURFdQ6MTFJzeA',
    appId: '1:688257544869:web:92a312a82fb76c15d3d34c',
    messagingSenderId: '688257544869',
    projectId: 'lost-found-22796',
    authDomain: 'lost-found-22796.firebaseapp.com',
    storageBucket: 'lost-found-22796.firebasestorage.app',
    databaseURL: 'https://lost-found-22796-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATqmZ8l53kMoTdkFAfdsURFdQ6MTFJzeA',
    appId: '1:688257544869:web:92a312a82fb76c15d3d34c',
    messagingSenderId: '688257544869',
    projectId: 'lost-found-22796',
    authDomain: 'lost-found-22796.firebaseapp.com',
    storageBucket: 'lost-found-22796.firebasestorage.app',
    databaseURL: 'https://lost-found-22796-default-rtdb.firebaseio.com',
  );

}